openapi: 3.0.3
info:
  title: Token-Based Pagination API
  version: 1.0.0
  description: An API that uses pageToken and pageSize for pagination with HMAC-signed tokens.
servers:
  - url: http://localhost:3000

paths:
  /items:
    get:
      summary: Retrieve items using token-based pagination
      parameters:
        - name: pageSize
          in: query
          description: Number of items to return per page
          schema:
            type: integer
            default: 10
        - name: pageToken
          in: query
          description: Base64-encoded HMAC-signed token representing the page offset
          schema:
            type: string
      responses:
        '200':
          description: A paginated list of items
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 1000
                  currentOffset:
                    type: integer
                    example: 20
                  currentPage:
                    type: integer
                    example: 3
                  pageSize:
                    type: integer
                    example: 10
                  nextPageToken:
                    type: string
                    nullable: true
                  previousPageToken:
                    type: string
                    nullable: true
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
        '401':
          description: Unauthorized
        '400':
          description: Invalid page token
      security:
        - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
